### PR TITLE
Example spec with fractional hours causing infinite loop

### PR DESCRIPTION
**Pull request by watsonbox**

### CODE REVIEW

**Comment by Intrepidd** [comment]
Thanks very appreciated. I or @jarthod will have a look soon

**Comment by watsonbox** [comment]
No problem.  Sorry I don't have time to look into this and provide a fix myself.

**Comment by watsonbox** [comment]
Well, I had time to come up with _a_ solution but probably not the most elegant one :).

**Comment by jarthod** [comment]
This last fix is good @watsonbox, thanks !

**Comment by Intrepidd** [comment]
Thanks for taking care of it Adrien 👍

**Comment by jarthod** [comment]
Released in `1.1.2`.

**Pull request merged**
