### PR TITLE
Fix deprecated warnings in Ruby 2.4.0+

### PR DESCRIPTION
**Pull request by mgka**
Ruby 2.4.0 unifies Fixnum and Bignum into Integer.

### CODE REVIEW

**Comment by jarthod** [comment]
I guess this still works for `<= 2.3` because `Fixnum < Integer`, right ?

**Comment by mgka** [comment]
@jarthod Yes, I tested on 2.4.0 and 2.3.1

**Comment by jarthod** [comment]
Sounds good, ok @Intrepidd  ?

**Comment by jarthod** [comment]
Could you please update the Travis config to check on 2.4 too :)

**Comment by mgka** [comment]
Updated.  Thanks!

**Comment by Intrepidd** [comment]
Looks good ! Tanks ! We'll merge when travis comes back

**Comment by jarthod** [comment]
There's a failure with `ruby 2.4` and `activesupport 3.2` (which is normal I guess, they are not compatible)
Can we exclude this (or mark as allowed failure) from the test matrix?

**Comment by Intrepidd** [comment]
Let's exclude the combination, it makes no sense to run it :)

**Comment by mgka** [comment]
I excluded ruby 2.4 and activesupport 3.2 combination. Please check :)

**Comment by Intrepidd** [comment]
🎉 Thanks for your contribution !

**Comment by srt32** [comment]
Thanks for this update! Would y'all consider a release to rubygems to allow builds with Ruby >= 2.4? 

Happy to help if possible.

Thanks!

**Comment by jarthod** [comment]
@Intrepidd can you do it?

**Comment by Intrepidd** [comment]
https://rubygems.org/gems/working_hours/versions/1.1.3

There you go @srt32

**Comment by srt32** [comment]
Thank you!

**Pull request merged**
